# Site settings

title: Thomas M. Moyer # Title of your site
email: tommoyer@gmail.com # Your contant email

description: > # this means to ignore newlines until "baseurl:"
  Homepage for Thomas M. Moyer, a computer and network security
  researcher at MIT Lincoln Laboratory.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thomasmoyer.org" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:     tmmoyer  # Replace this with your Twitter username
github_username:      tommoyer  # Replace this with your GitHub username
linkedin_username:    thomas-moyer-21b0ba8 # Replace this with your LinkedIn username
google_plus_username: +ThomasMoyer324  # Replace this with your Google+ username
facebook_username:    tmoyer324  # Replace this with your Facebook username
#dribbble_username:    example  # Replace this with your Dribbble username

# Build settings
markdown: kramdown
