# Site settings

title: Thomas M. Moyer # Title of your site
email: tommoyer@gmail.com # Your contant email

description: > # this means to ignore newlines until "baseurl:"
  Homepage for Thomas M. Moyer, a computer and network security
  researcher at MIT Lincoln Laboratory.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thomasmoyer.org" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:     tmmoyer  # Replace this with your Twitter username
github_username:      tommoyer  # Replace this with your GitHub username
linkedin_username:    thomas-moyer-21b0ba8 # Replace this with your LinkedIn username
google_plus_username: +ThomasMoyer324  # Replace this with your Google+ username
facebook_username:    tmoyer324  # Replace this with your Facebook username
keybase_username:    tommoyer  # Replace this with your Keybase username
bitbucket_username:    tmoyer  # Replace this with your bitbucket username
#dribbble_username:    example  # Replace this with your Dribbble username

# Build settings
markdown: kramdown

collections:
 news:
   output: false

permalink: pretty

defaults:
  - scope:
      path: ""
      type: news
    values:
      layout: page

exclude: ['Rakefile', 'LICENSE.txt', 'README.txt', 'files/Moyer_cv.tex', 'files/moyer.bib', 'sass', '*/metadata', 'Gemfile', 'Gemfile.lock', 'README.md', 'pubs/moyer.bib', 'pubs/*.csl', 'vendor', 'files/auto', 'files/*.aux', 'files/*.bbl', 'files/*.blg', 'files/*.fdb_latexmk', 'files/*.fls', 'files/*.log', 'files/*.out']
include: ['.well-known']

# jekyll-scholar configurations
scholar:
  style: ./pubs/ieee.csl
  locale: en
  sort_by: year,month
  order: descending
  source: ./pubs
  bibliography: moyer.bib
  details_dir: ./pubs/details
  query: "@*[public!=no]"
  parse_months: true
  bibliography_template: pubs
  repository: pubs/

  # Scholar has changed the way it renders bib tags
  # Need to look at more at the defaults.
  bibliography_list_tag: "ul"

# jekyll-scholar-extras configurations
scholar-extras:
# TODO Options need to be reworked through

lsi: false
safe: false
