version: '3.7'

services:
  www:
    container_name: www
    restart: unless-stopped
    build: .
    image: tommoyer/www
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      - CERTBOT_EMAIL=tommoyer@gmail.com
  